version: '3'
services: 
    loginapplication:
        build: 
            context: LoginApplication/
        ports: 
            - "8069:8069"
        restart: always
    simplecache:
        build: 
            context: CacheManagement/
        ports: 
            - "8070:8070"
        restart: always
    apachecassandra:
        image: 'cassandra'
        ports:
            - "9042:9042"
            - "9160:9160"
            - "7199:7199"
        container_name: 'apachecassandra'